<?php

// scoper-autoload.php @generated by PhpScoper

$loader = require_once __DIR__.'/autoload.php';

// Exposed classes. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#exposing-classes
if (!class_exists('ComposerAutoloaderInit5f010441a0816e825606affd73468707', false) && !interface_exists('ComposerAutoloaderInit5f010441a0816e825606affd73468707', false) && !trait_exists('ComposerAutoloaderInit5f010441a0816e825606affd73468707', false)) {
    spl_autoload_call('Branda_Vendor\ComposerAutoloaderInit5f010441a0816e825606affd73468707');
}
if (!class_exists('Google_Task_Composer', false) && !interface_exists('Google_Task_Composer', false) && !trait_exists('Google_Task_Composer', false)) {
    spl_autoload_call('Branda_Vendor\Google_Task_Composer');
}
if (!class_exists('Google_AccessToken_Revoke', false) && !interface_exists('Google_AccessToken_Revoke', false) && !trait_exists('Google_AccessToken_Revoke', false)) {
    spl_autoload_call('Branda_Vendor\Google_AccessToken_Revoke');
}
if (!class_exists('Google_AccessToken_Verify', false) && !interface_exists('Google_AccessToken_Verify', false) && !trait_exists('Google_AccessToken_Verify', false)) {
    spl_autoload_call('Branda_Vendor\Google_AccessToken_Verify');
}
if (!class_exists('Google_AuthHandler_AuthHandlerFactory', false) && !interface_exists('Google_AuthHandler_AuthHandlerFactory', false) && !trait_exists('Google_AuthHandler_AuthHandlerFactory', false)) {
    spl_autoload_call('Branda_Vendor\Google_AuthHandler_AuthHandlerFactory');
}
if (!class_exists('Google_AuthHandler_Guzzle5AuthHandler', false) && !interface_exists('Google_AuthHandler_Guzzle5AuthHandler', false) && !trait_exists('Google_AuthHandler_Guzzle5AuthHandler', false)) {
    spl_autoload_call('Branda_Vendor\Google_AuthHandler_Guzzle5AuthHandler');
}
if (!class_exists('Google_AuthHandler_Guzzle6AuthHandler', false) && !interface_exists('Google_AuthHandler_Guzzle6AuthHandler', false) && !trait_exists('Google_AuthHandler_Guzzle6AuthHandler', false)) {
    spl_autoload_call('Branda_Vendor\Google_AuthHandler_Guzzle6AuthHandler');
}
if (!class_exists('Google_AuthHandler_Guzzle7AuthHandler', false) && !interface_exists('Google_AuthHandler_Guzzle7AuthHandler', false) && !trait_exists('Google_AuthHandler_Guzzle7AuthHandler', false)) {
    spl_autoload_call('Branda_Vendor\Google_AuthHandler_Guzzle7AuthHandler');
}
if (!class_exists('Google_Client', false) && !interface_exists('Google_Client', false) && !trait_exists('Google_Client', false)) {
    spl_autoload_call('Branda_Vendor\Google_Client');
}
if (!class_exists('Google_Collection', false) && !interface_exists('Google_Collection', false) && !trait_exists('Google_Collection', false)) {
    spl_autoload_call('Branda_Vendor\Google_Collection');
}
if (!class_exists('Google_Exception', false) && !interface_exists('Google_Exception', false) && !trait_exists('Google_Exception', false)) {
    spl_autoload_call('Branda_Vendor\Google_Exception');
}
if (!class_exists('Google_Http_Batch', false) && !interface_exists('Google_Http_Batch', false) && !trait_exists('Google_Http_Batch', false)) {
    spl_autoload_call('Branda_Vendor\Google_Http_Batch');
}
if (!class_exists('Google_Http_MediaFileUpload', false) && !interface_exists('Google_Http_MediaFileUpload', false) && !trait_exists('Google_Http_MediaFileUpload', false)) {
    spl_autoload_call('Branda_Vendor\Google_Http_MediaFileUpload');
}
if (!class_exists('Google_Http_REST', false) && !interface_exists('Google_Http_REST', false) && !trait_exists('Google_Http_REST', false)) {
    spl_autoload_call('Branda_Vendor\Google_Http_REST');
}
if (!class_exists('Google_Model', false) && !interface_exists('Google_Model', false) && !trait_exists('Google_Model', false)) {
    spl_autoload_call('Branda_Vendor\Google_Model');
}
if (!class_exists('Google_Service', false) && !interface_exists('Google_Service', false) && !trait_exists('Google_Service', false)) {
    spl_autoload_call('Branda_Vendor\Google_Service');
}
if (!class_exists('Google_Service_Exception', false) && !interface_exists('Google_Service_Exception', false) && !trait_exists('Google_Service_Exception', false)) {
    spl_autoload_call('Branda_Vendor\Google_Service_Exception');
}
if (!class_exists('Google_Service_Resource', false) && !interface_exists('Google_Service_Resource', false) && !trait_exists('Google_Service_Resource', false)) {
    spl_autoload_call('Branda_Vendor\Google_Service_Resource');
}
if (!class_exists('Google_Task_Exception', false) && !interface_exists('Google_Task_Exception', false) && !trait_exists('Google_Task_Exception', false)) {
    spl_autoload_call('Branda_Vendor\Google_Task_Exception');
}
if (!class_exists('Google_Task_Retryable', false) && !interface_exists('Google_Task_Retryable', false) && !trait_exists('Google_Task_Retryable', false)) {
    spl_autoload_call('Branda_Vendor\Google_Task_Retryable');
}
if (!class_exists('Google_Task_Runner', false) && !interface_exists('Google_Task_Runner', false) && !trait_exists('Google_Task_Runner', false)) {
    spl_autoload_call('Branda_Vendor\Google_Task_Runner');
}
if (!class_exists('Google_Utils_UriTemplate', false) && !interface_exists('Google_Utils_UriTemplate', false) && !trait_exists('Google_Utils_UriTemplate', false)) {
    spl_autoload_call('Branda_Vendor\Google_Utils_UriTemplate');
}

// Exposed functions. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/configuration.md#exposing-functions
if (!function_exists('phpseclib_safe_serialize')) {
    function phpseclib_safe_serialize() {
        return \Branda_Vendor\phpseclib_safe_serialize(...func_get_args());
    }
}
if (!function_exists('composerRequire5f010441a0816e825606affd73468707')) {
    function composerRequire5f010441a0816e825606affd73468707() {
        return \Branda_Vendor\composerRequire5f010441a0816e825606affd73468707(...func_get_args());
    }
}
if (!function_exists('zend_monitor_custom_event')) {
    function zend_monitor_custom_event() {
        return \Branda_Vendor\zend_monitor_custom_event(...func_get_args());
    }
}
if (!function_exists('uri_template')) {
    function uri_template() {
        return \Branda_Vendor\uri_template(...func_get_args());
    }
}
if (!function_exists('oauth2client_php_autoload')) {
    function oauth2client_php_autoload() {
        return \Branda_Vendor\oauth2client_php_autoload(...func_get_args());
    }
}
if (!function_exists('RandomCompat_intval')) {
    function RandomCompat_intval() {
        return \Branda_Vendor\RandomCompat_intval(...func_get_args());
    }
}
if (!function_exists('RandomCompat_strlen')) {
    function RandomCompat_strlen() {
        return \Branda_Vendor\RandomCompat_strlen(...func_get_args());
    }
}
if (!function_exists('RandomCompat_substr')) {
    function RandomCompat_substr() {
        return \Branda_Vendor\RandomCompat_substr(...func_get_args());
    }
}

return $loader;
