<?php
/**
 * Dashicons list
 * based on https://developer.wordpress.org/resource/dashicons/
 * date: 2018-09-08
 */

$_branda_dashicons_list = array(
	'admin menu'                 => array(
		'title' => __( 'Admin Menu', 'ub' ),
		'icons' => array(
			'f333' => 'menu',
			'f319' => 'admin-site',
			'f226' => 'dashboard',
			'f109' => 'admin-post',
			'f104' => 'admin-media',
			'f103' => 'admin-links',
			'f105' => 'admin-page',
			'f101' => 'admin-comments',
			'f100' => 'admin-appearance',
			'f106' => 'admin-plugins',
			'f110' => 'admin-users',
			'f107' => 'admin-tools',
			'f108' => 'admin-settings',
			'f112' => 'admin-network',
			'f102' => 'admin-home',
			'f111' => 'admin-generic',
			'f148' => 'admin-collapse',
			'f536' => 'filter',
			'f540' => 'admin-customizer',
			'f541' => 'admin-multisite',
		),
	),

	'welcome screen'             => array(
		'title' => __( 'Welcome Screen', 'ub' ),
		'icons' => array(
			'f119' => 'welcome-write-blog',
			'f119' => 'welcome-edit-page',
			'f133' => 'welcome-add-page',
			'f115' => 'welcome-view-site',
			'f116' => 'welcome-widgets-menus',
			'f117' => 'welcome-comments',
			'f118' => 'welcome-learn-more',
		),
	),

	'post formats'               => array(
		'title' => __( 'Post Formats', 'ub' ),
		'icons' => array(
			'f109' => 'format-standard',
			'f123' => 'format-aside',
			'f128' => 'format-image',
			'f161' => 'format-gallery',
			'f126' => 'format-video',
			'f130' => 'format-status',
			'f122' => 'format-quote',
			'f103' => 'format-links',
			'f125' => 'format-chat',
			'f127' => 'format-audio',
			'f306' => 'camera',
			'f232' => 'images-alt',
			'f233' => 'images-alt2',
			'f234' => 'video-alt',
			'f235' => 'video-alt2',
			'f236' => 'video-alt3',

		),
	),
	'media'                      => array(
		'title' => __( 'Media', 'ub' ),
		'icons' => array(
			'f501' => 'media-archive',
			'f500' => 'media-audio',
			'f499' => 'media-code',
			'f498' => 'media-default',
			'f497' => 'media-document',
			'f496' => 'media-interactive',
			'f495' => 'media-spreadsheet',
			'f491' => 'media-text',
			'f490' => 'media-video',
			'f492' => 'playlist-audio',
			'f493' => 'playlist-video',
			'f522' => 'controls-play',
			'f523' => 'controls-pause',
			'f519' => 'controls-forward',
			'f517' => 'controls-skipforward',
			'f518' => 'controls-back',
			'f516' => 'controls-skipback',
			'f515' => 'controls-repeat',
			'f521' => 'controls-volumeon',
			'f520' => 'controls-volumeoff',

		),
	),

	'image editing'              => array(
		'title' => __( 'Image Editing', 'ub' ),
		'icons' => array(
			'f165' => 'image-crop',
			'f531' => 'image-rotate',
			'f166' => 'image-rotate-left',
			'f167' => 'image-rotate-right',
			'f168' => 'image-flip-vertical',
			'f169' => 'image-flip-horizontal',
			'f533' => 'image-filter',
			'f171' => 'undo',
			'f172' => 'redo',
		),
	),

	'tinymce'                    => array(
		'title' => __( 'TinyMCE', 'ub' ),
		'icons' => array(
			'f200' => 'editor-bold',
			'f201' => 'editor-italic',
			'f203' => 'editor-ul',
			'f204' => 'editor-ol',
			'f205' => 'editor-quote',
			'f206' => 'editor-alignleft',
			'f207' => 'editor-aligncenter',
			'f208' => 'editor-alignright',
			'f209' => 'editor-insertmore',
			'f210' => 'editor-spellcheck',
			'f211' => 'editor-distractionfree',
			'f211' => 'editor-expand',
			'f506' => 'editor-contract',
			'f212' => 'editor-kitchensink',
			'f213' => 'editor-underline',
			'f214' => 'editor-justify',
			'f215' => 'editor-textcolor',
			'f216' => 'editor-paste-word',
			'f217' => 'editor-paste-text',
			'f218' => 'editor-removeformatting',
			'f219' => 'editor-video',
			'f220' => 'editor-customchar',
			'f221' => 'editor-outdent',
			'f222' => 'editor-indent',
			'f223' => 'editor-help',
			'f224' => 'editor-strikethrough',
			'f225' => 'editor-unlink',
			'f320' => 'editor-rtl',
			'f474' => 'editor-break',
			'f475' => 'editor-code',
			'f476' => 'editor-paragraph',
			'f535' => 'editor-table',

		),
	),

	'posts'                      => array(
		'title' => __( 'Posts Screen', 'ub' ),
		'icons' => array(
			'f135' => 'align-left',
			'f136' => 'align-right',
			'f134' => 'align-center',
			'f138' => 'align-none',
			'f160' => 'lock',
			'f528' => 'unlock',
			'f145' => 'calendar',
			'f508' => 'calendar-alt',
			'f177' => 'visibility',
			'f530' => 'hidden',
			'f173' => 'post-status',
			'f464' => 'edit',
			'f182' => 'trash',
			'f537' => 'sticky',
		),
	),

	'sorting'                    => array(
		'title' => __( 'Sorting', 'ub' ),
		'icons' => array(
			'f504' => 'external',
			'f142' => 'arrow-up',
			'f140' => 'arrow-down',
			'f139' => 'arrow-right',
			'f141' => 'arrow-left',
			'f342' => 'arrow-up-alt',
			'f346' => 'arrow-down-alt',
			'f344' => 'arrow-right-alt',
			'f340' => 'arrow-left-alt',
			'f343' => 'arrow-up-alt2',
			'f347' => 'arrow-down-alt2',
			'f345' => 'arrow-right-alt2',
			'f341' => 'arrow-left-alt2',
			'f156' => 'sort',
			'f229' => 'leftright',
			'f503' => 'randomize',
			'f163' => 'list-view',
			'f164' => 'exerpt-view',
			'f509' => 'grid-view',
			'f545' => 'move',

		),
	),

	'social'                     => array(
		'title' => __( 'Social', 'ub' ),
		'icons' => array(
			'f237' => 'share',
			'f240' => 'share-alt',
			'f242' => 'share-alt2',
			'f301' => 'twitter',
			'f303' => 'rss',
			'f465' => 'email',
			'f466' => 'email-alt',
			'f304' => 'facebook',
			'f305' => 'facebook-alt',
			'f462' => 'googleplus',
			'f325' => 'networking',

		),
	),

	'icons'                      => array(
		'title' => __( 'WordPress.org Specific: Jobs, Profiles, WordCamps', 'ub' ),
		'icons' => array(
			'f308' => 'hammer',
			'f309' => 'art',
			'f310' => 'migrate',
			'f311' => 'performance',
			'f483' => 'universal-access',
			'f507' => 'universal-access-alt',
			'f486' => 'tickets',
			'f484' => 'nametag',
			'f481' => 'clipboard',
			'f487' => 'heart',
			'f488' => 'megaphone',
			'f489' => 'schedule',
		),
	),
	'internal/products'          => array(
		'title' => __( 'Products', 'ub' ),
		'icons' => array(
			'f120' => 'wordpress',
			'f324' => 'wordpress-alt',
			'f157' => 'pressthis',
			'f463' => 'update',
			'f180' => 'screenoptions',
			'f348' => 'info',
			'f174' => 'cart',
			'f175' => 'feedback',
			'f176' => 'cloud',
			'f326' => 'translation',

		),
	),

	'taxonomies'                 => array(
		'title' => __( 'Taxonomies', 'ub' ),
		'icons' => array(
			'f323' => 'tag',
			'f318' => 'category',
		),
	),

	'widgets'                    => array(
		'title' => __( 'Widgets', 'ub' ),
		'icons' => array(
			'f480' => 'archive',
			'f479' => 'tagcloud',
			'f478' => 'text',
		),
	),

	'alerts/notifications/flags' => array(
		'title' => __( 'Notifications', 'ub' ),
		'icons' => array(
			'f147' => 'yes',
			'f158' => 'no',
			'f335' => 'no-alt',
			'f132' => 'plus',
			'f502' => 'plus-alt',
			'f460' => 'minus',
			'f153' => 'dismiss',
			'f159' => 'marker',
			'f155' => 'star-filled',
			'f459' => 'star-half',
			'f154' => 'star-empty',
			'f227' => 'flag',
			'f534' => 'warning',
		),
	),

	'misc/cpt'                   => array(
		'title' => __( 'Misc', 'ub' ),
		'icons' => array(
			'f230' => 'location',
			'f231' => 'location-alt',
			'f178' => 'vault',
			'f332' => 'shield',
			'f334' => 'shield-alt',
			'f468' => 'sos',
			'f179' => 'search',
			'f181' => 'slides',
			'f183' => 'analytics',
			'f184' => 'chart-pie',
			'f185' => 'chart-bar',
			'f238' => 'chart-line',
			'f239' => 'chart-area',
			'f307' => 'groups',
			'f338' => 'businessman',
			'f336' => 'id',
			'f337' => 'id-alt',
			'f312' => 'products',
			'f313' => 'awards',
			'f314' => 'forms',
			'f473' => 'testimonial',
			'f322' => 'portfolio',
			'f330' => 'book',
			'f331' => 'book-alt',
			'f316' => 'download',
			'f317' => 'upload',
			'f321' => 'backup',
			'f469' => 'clock',
			'f339' => 'lightbulb',
			'f482' => 'microphone',
			'f472' => 'desktop',
			'f547' => 'laptop',
			'f471' => 'tablet',
			'f470' => 'smartphone',
			'f525' => 'phone',
			'f510' => 'index-card',
			'f511' => 'carrot',
			'f512' => 'building',
			'f513' => 'store',
			'f514' => 'album',
			'f527' => 'palmtree',
			'f524' => 'tickets-alt',
			'f526' => 'money',
			'f328' => 'smiley',
			'f529' => 'thumbs-up',
			'f542' => 'thumbs-down',
			'f538' => 'layout',
			'f546' => 'paperclip',
		),
	),
);

return $_branda_dashicons_list;

