language: php
php:
  - 7.4
  - 8.0
  - 8.1
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
matrix:
  include:
    - php: 8.0
      env: WP_VERSION=trunk WP_MULTISITE=0
    - php: 8.0
      env: WP_VERSION=trunk WP_MULTISITE=1
allow_failures:
  - php: 8.1
services:
  - mysql
install:
  - composer install
  - bash tests/install-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
script:
  - vendor/bin/phpunit
notifications:
    email: false
