<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'Symfony\\Polyfill\\Php70\\' => array($vendorDir . '/symfony/polyfill-php70'),
    'Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Symfony\\Polyfill\\Intl\\Idn\\' => array($vendorDir . '/symfony/polyfill-intl-idn'),
    'Branda_Vendor\\phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Branda_Vendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Branda_Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Branda_Vendor\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Branda_Vendor\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Branda_Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Branda_Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Branda_Vendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Branda_Vendor\\Google\\Service\\' => array($vendorDir . '/google/apiclient-services/src'),
    'Branda_Vendor\\Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'Branda_Vendor\\Google\\' => array($vendorDir . '/google/apiclient/src'),
    'Branda_Vendor\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
);
